"""Start

Revision ID: 4ffcc21505d3
Revises: 
Create Date: 2025-03-24 10:57:30.597622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffcc21505d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ARRAY', 'MATRIX', 'TEXT', 'IMAGE', 'AUDIO', 'VIDEO', name='testdatatype'), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_data_id'), 'default_data', ['id'], unique=False)
    op.create_table('lesson_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_list_id'), 'lesson_list', ['id'], unique=False)
    op.create_table('performance_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread', sa.Integer(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_evaluation_id'), 'performance_evaluation', ['id'], unique=False)
    op.create_table('processing_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ARRAY', 'MATRIX', 'TEXT', 'IMAGE', 'AUDIO', 'VIDEO', name='testdatatype'), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_data_id'), 'processing_data', ['id'], unique=False)
    op.create_table('user_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_list_id'), 'user_list', ['id'], unique=False)
    op.create_table('lesson_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'HEADER', 'CODE', name='lessondatatype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_data_id'), 'lesson_data', ['id'], unique=False)
    op.create_table('research_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['lesson_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_list_id'), 'research_list', ['id'], unique=False)
    op.create_table('user_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_lesson_id'), 'user_lesson', ['id'], unique=False)
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameters_id'), 'parameters', ['id'], unique=False)
    op.create_table('data_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('parameters_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['default_data.id'], ),
    sa.ForeignKeyConstraint(['parameters_id'], ['parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_parameters_id'), 'data_parameters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_parameters_id'), table_name='data_parameters')
    op.drop_table('data_parameters')
    op.drop_index(op.f('ix_parameters_id'), table_name='parameters')
    op.drop_table('parameters')
    op.drop_index(op.f('ix_user_lesson_id'), table_name='user_lesson')
    op.drop_table('user_lesson')
    op.drop_index(op.f('ix_research_list_id'), table_name='research_list')
    op.drop_table('research_list')
    op.drop_index(op.f('ix_lesson_data_id'), table_name='lesson_data')
    op.drop_table('lesson_data')
    op.drop_index(op.f('ix_user_list_id'), table_name='user_list')
    op.drop_table('user_list')
    op.drop_index(op.f('ix_processing_data_id'), table_name='processing_data')
    op.drop_table('processing_data')
    op.drop_index(op.f('ix_performance_evaluation_id'), table_name='performance_evaluation')
    op.drop_table('performance_evaluation')
    op.drop_index(op.f('ix_lesson_list_id'), table_name='lesson_list')
    op.drop_table('lesson_list')
    op.drop_index(op.f('ix_default_data_id'), table_name='default_data')
    op.drop_table('default_data')
    # ### end Alembic commands ###
