"""Start

Revision ID: ab6b0b57c653
Revises: 
Create Date: 2025-03-28 13:42:04.260408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6b0b57c653'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_list_id'), 'user_list', ['id'], unique=False)
    op.create_table('default_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ARRAY', 'MATRIX', 'TEXT', 'IMAGE', 'AUDIO', 'VIDEO', name='testdatatype'), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_data_id'), 'default_data', ['id'], unique=False)
    op.create_table('lesson_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_list_id'), 'lesson_list', ['id'], unique=False)
    op.create_table('test_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_list_id'), 'test_list', ['id'], unique=False)
    op.create_table('arguments_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arguments_list_id'), 'arguments_list', ['id'], unique=False)
    op.create_table('data_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('default_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_data_id'], ['default_data.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_list_id'), 'data_list', ['id'], unique=False)
    op.create_table('lesson_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'HEADER', 'CODE', name='lessondatatype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_data_id'), 'lesson_data', ['id'], unique=False)
    op.create_table('user_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_lesson_id'), 'user_lesson', ['id'], unique=False)
    op.create_table('data_arguments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('args_id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('processing_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['args_id'], ['arguments_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_id'], ['data_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_arguments_id'), 'data_arguments', ['id'], unique=False)
    op.create_table('performance_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread', sa.Integer(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('processing_data', sa.String(), nullable=True),
    sa.Column('data_arguments_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_arguments_id'], ['data_arguments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_values_id'), 'performance_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_values_id'), table_name='performance_values')
    op.drop_table('performance_values')
    op.drop_index(op.f('ix_data_arguments_id'), table_name='data_arguments')
    op.drop_table('data_arguments')
    op.drop_index(op.f('ix_user_lesson_id'), table_name='user_lesson')
    op.drop_table('user_lesson')
    op.drop_index(op.f('ix_lesson_data_id'), table_name='lesson_data')
    op.drop_table('lesson_data')
    op.drop_index(op.f('ix_data_list_id'), table_name='data_list')
    op.drop_table('data_list')
    op.drop_index(op.f('ix_arguments_list_id'), table_name='arguments_list')
    op.drop_table('arguments_list')
    op.drop_index(op.f('ix_test_list_id'), table_name='test_list')
    op.drop_table('test_list')
    op.drop_index(op.f('ix_lesson_list_id'), table_name='lesson_list')
    op.drop_table('lesson_list')
    op.drop_index(op.f('ix_default_data_id'), table_name='default_data')
    op.drop_table('default_data')
    op.drop_index(op.f('ix_user_list_id'), table_name='user_list')
    op.drop_table('user_list')
    # ### end Alembic commands ###
